### ISSUE TITLE
In Xcode: An Overview

### ISSUE THREAD

**Issue by amyjoscelyn** [learn-co-curriculum/reading-ios-xcode-overview#3]
@markedwardmurray 

The **note** directly under Xcode Anatomy 101 mentions how you can "open the lab in next the lesson" (awk), Your-First-NSLog.

Since this is in the middle of the Basics, Your-First-NSLog is no longer directly after, and by this point there have been three labs (two being the code-alongs), so this statement no longer feels as necessary as it once was.

I actually remember suggesting edits to this awhile ago, and I can still see the awkward tensing or grammatical errors that I had pointed out.  Would you like me to edit those for you?

**Comment by markedwardmurray** [comment]
it's because i moved the reading around in the track without rewriting it, so the voice is awkward. it's on my todo list to rework the unit it belongs to in September.

**Comment by AnnJohn** [comment]
@markedwardmurray are you still working on this issue? If yes, remove icebox label and set a tentative deadline. If not, just unassign yourself. Thanks.

**Comment by markedwardmurray** [comment]
this is one we'll talk about with Joe on Wed
